Feature/time-formatter
bl1ndy/t-39-rack-app pull request #1
Opened 2022-07-17 14:05 UTC by bl1ndy

2022-07-17 18:38 UTC, BubuntuClu requested changes

2022-07-17 18:38 UTC, BubuntuClu commented on middleware/time_formatter.rb
> +class TimeFormatter
Rack приложение
Это данный класс. В его обязанности входит обработка запроса и формирование ответа в формате совместимом с rack. То есть здесь мы проверяем правильный ли пришёл URL или нужно отдать 404, хватает ли параметров или нужно отдать 400-й статус. При этом логику формирования тела ответа мы помещаем в отдельный класс бизнес логики.

Класс бизнес логики
Это отдельный простой Ruby класс, который может называться, например, TimeFormatter. Он ничего не должен знать о rack приложении, иными словами о том кто и где будет его использовать. Мы можем вызывать его из консоли или в другом Ruby приложении без HTTP API интерфейса.

2022-07-17 18:38 UTC, BubuntuClu commented on middleware/time_formatter.rb
> +    [status, headers, body]
сделай методя для ответа `response` и вызывай его в нужных местах твоего кода. внутри используй `Rack::Response`

2022-07-17 18:38 UTC, BubuntuClu commented on middleware/time_formatter.rb
> +      year: @current_time.year,
сделай значениями ключей код для метода `strftime`, потмо собрав ключи ты сможешь получить нужную строку

2022-07-17 18:38 UTC, BubuntuClu commented on middleware/time_formatter.rb
> +    @formats.map { |part| @available_formats[part.to_sym].to_s.rjust(2, '0') }
ты два раза проходишься по массиву форматов, это не оптимально. надо за один обход понять где валидные/невалидные форматы

2022-07-18 17:50 UTC, BubuntuClu requested changes

2022-07-18 18:29 UTC, bl1ndy commented on formatters/time_formatter.rb
> +    @time = time
Форматтер умеет работать не только с текущим временем, но и с любым переданным

2022-07-18 18:31 UTC, bl1ndy commented on formatters/time_formatter.rb
> +    valid_formats = []
Локальная переменная только для метода `format`

2022-07-19 07:12 UTC, BubuntuClu commented on middleware/time_app.rb
> +      response("Format not found\n", 400, headers)
почему это ошибка? не передали никакой ключ, в ответ будет пустая строка, это ведь не ошибка

2022-07-19 07:12 UTC, BubuntuClu commented on middleware/time_app.rb
> +  def status
да не нужны тебе эти методы. ты лишний раз гоняешь одну и туже проверку, только в разных методах
`@unknown_formats.any?` - вот это ты проверяешь и в статусе и в теле. зачем тебе проверять это если по структуре кода тебе и так должно быть понятно какой статус/тело надо отдать.
если `@unknown_formats.any?` будет "тяжелым" запросом то ты дважды будешь делать "тяжелую" првоерку - не оптимально

2022-07-19 07:12 UTC, BubuntuClu commented on formatters/time_formatter.rb
> +    valid_formats = []
ну, у тебя все переменные только для этого метода, потому что у тебя других и нет)
лучше разделить логику кода на разные методы, чем делать один мега метод, который делает все

2022-07-19 08:15 UTC, merged